# Generated by Django 5.1.7 on 2025-04-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_by',
        ),
    ]
