# Generated by Django 5.1.7 on 2025-04-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0003_material_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='material',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received')], default='ordered', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
