# Generated by Django 5.1.7 on 2025-04-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0005_alter_material_name_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tracking_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
