# Generated by Django 5.1.7 on 2025-04-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0006_inventory_expiry_date_inventory_tracking_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tracking_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
