# Generated by Django 5.1.7 on 2025-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0008_batch_batchitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='batchitem',
            name='tracking_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
