# Generated by Django 5.1.7 on 2025-04-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0009_alter_batchitem_options_batchitem_tracking_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='tracking_key',
        ),
    ]
