# Generated by Django 5.1.7 on 2025-04-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0010_remove_batchitem_tracking_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_key',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='status',
        ),
    ]
