# Generated by Django 5.1.7 on 2025-04-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0015_fix_purchase_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tracking_key',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tracking_key_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='qb_trace.trackingkey'),
        ),
    ]
