# Generated by Django 5.1.7 on 2025-04-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0016_remove_purchaseorderitem_tracking_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tracking_key_id',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tracking_key',
            field=models.ForeignKey(blank=True, db_column='tracking_key_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='qb_trace.trackingkey'),
        ),
    ]
