# Generated by Django 5.1.7 on 2025-04-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0017_remove_purchaseorderitem_tracking_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='material_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='tracking_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qb_trace.trackingkey'),
        ),
    ]
