# Generated by Django 5.1.7 on 2025-04-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0018_alter_purchaseorderitem_material_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('completed', 'Completed')], default='ordered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_lots', to='qb_trace.batch')),
            ],
            options={
                'db_table': 'serial_lots',
            },
        ),
        migrations.CreateModel(
            name='SerialLotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qb_trace.inventory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qb_trace.material')),
                ('serial_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qb_trace.seriallot')),
                ('tracking_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qb_trace.trackingkey')),
            ],
            options={
                'db_table': 'serial_lot_items',
            },
        ),
        migrations.RunSQL(
            sql=[
                'DROP TABLE IF EXISTS qb_trace_seriallot CASCADE;',
                'DROP TABLE IF EXISTS qb_trace_seriallotitem CASCADE;',
            ],
            reverse_sql=[]
        ),
    ]
