# Generated by Django 5.1.7 on 2025-04-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0019_create_serial_lot_tables'),
        ('qb_trace', '0019_seriallot_seriallotitem'),
    ]

    operations = [
    ]
