# Generated by Django 5.1.7 on 2025-04-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0020_merge_20250410_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriallot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='seriallotitem',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='seriallot',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seriallot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
