# Generated by Django 5.1.7 on 2025-04-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0024_alter_inventory_options_inventory_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='serial_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='qb_trace.seriallot'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tracking_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='qb_trace.trackingkey'),
        ),
    ]
