# Generated by Django 5.1.7 on 2025-04-11 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0025_salesorderitem_serial_lot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='material_name',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='qb_trace.material'),
        ),
    ]
