# Generated by Django 5.1.7 on 2025-04-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_trace', '0026_rename_material_name_salesorderitem_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='material_name',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='qb_trace.material'),
        ),
    ]
